#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0000000
#define STDOUT_BASEADDRESS 0xE0000000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_ZYNQ
 
/* Definition for xilinx interrupt wrapper support  */
#define XIL_INTERRUPT
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver CANPS */
#define XPAR_XCANPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_CAN_0 */
#define XPAR_PS7_CAN_0_DEVICE_ID 0
#define XPAR_PS7_CAN_0_BASEADDR 0xE0008000
#define XPAR_PS7_CAN_0_HIGHADDR 0xE0008FFF
#define XPAR_PS7_CAN_0_CAN_CLK_FREQ_HZ 100000000


/* Definitions for peripheral PS7_CAN_1 */
#define XPAR_PS7_CAN_1_DEVICE_ID 1
#define XPAR_PS7_CAN_1_BASEADDR 0xE0009000
#define XPAR_PS7_CAN_1_HIGHADDR 0xE0009FFF
#define XPAR_PS7_CAN_1_CAN_CLK_FREQ_HZ 100000000


/******************************************************************/

/* Canonical definitions for peripheral PS7_CAN_0 */
#define XPAR_XCANPS_0_DEVICE_ID XPAR_PS7_CAN_0_DEVICE_ID
#define XPAR_XCANPS_0_BASEADDR 0xE0008000
#define XPAR_XCANPS_0_HIGHADDR 0xE0008FFF
#define XPAR_XCANPS_0_CAN_CLK_FREQ_HZ 100000000

/* Canonical definitions for peripheral PS7_CAN_1 */
#define XPAR_XCANPS_1_DEVICE_ID XPAR_PS7_CAN_1_DEVICE_ID
#define XPAR_XCANPS_1_BASEADDR 0xE0009000
#define XPAR_XCANPS_1_HIGHADDR 0xE0009FFF
#define XPAR_XCANPS_1_CAN_CLK_FREQ_HZ 100000000


/******************************************************************/


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x3FFFFFFF


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0U
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000U
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000U
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FFU


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50
#define XPAR_PS7_ETHERNET_0_ENET_TSU_CLK_FREQ_HZ 0


/* Definitions for peripheral PS7_ETHERNET_1 */
#define XPAR_PS7_ETHERNET_1_DEVICE_ID 1
#define XPAR_PS7_ETHERNET_1_BASEADDR 0xE000C000
#define XPAR_PS7_ETHERNET_1_HIGHADDR 0xE000CFFF
#define XPAR_PS7_ETHERNET_1_ENET_CLK_FREQ_HZ 125000000
#define XPAR_PS7_ETHERNET_1_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_1_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_1_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_1_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_1_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_1_ENET_SLCR_10MBPS_DIV1 50
#define XPAR_PS7_ETHERNET_1_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PS7_ETHERNET_0_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
#define XPAR_PS7_ETHERNET_1_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_1_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PS7_ETHERNET_1 */
#define XPAR_XEMACPS_1_DEVICE_ID XPAR_PS7_ETHERNET_1_DEVICE_ID
#define XPAR_XEMACPS_1_BASEADDR 0xE000C000
#define XPAR_XEMACPS_1_HIGHADDR 0xE000CFFF
#define XPAR_XEMACPS_1_ENET_CLK_FREQ_HZ 125000000
#define XPAR_XEMACPS_1_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_1_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_1_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_1_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_1_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_1_ENET_SLCR_10Mbps_DIV1 50
#define XPAR_XEMACPS_1_ENET_TSU_CLK_FREQ_HZ 0


/******************************************************************/


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_0 */
#define XPAR_UART_AXI_UART16550_BSM_0_BASEADDR 0x43C40000
#define XPAR_UART_AXI_UART16550_BSM_0_HIGHADDR 0x43C4FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_1 */
#define XPAR_UART_AXI_UART16550_BSM_1_BASEADDR 0x43C20000
#define XPAR_UART_AXI_UART16550_BSM_1_HIGHADDR 0x43C2FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_10 */
#define XPAR_UART_AXI_UART16550_BSM_10_BASEADDR 0x43C50000
#define XPAR_UART_AXI_UART16550_BSM_10_HIGHADDR 0x43C5FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_11 */
#define XPAR_UART_AXI_UART16550_BSM_11_BASEADDR 0x43D40000
#define XPAR_UART_AXI_UART16550_BSM_11_HIGHADDR 0x43D4FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_2 */
#define XPAR_UART_AXI_UART16550_BSM_2_BASEADDR 0x43C30000
#define XPAR_UART_AXI_UART16550_BSM_2_HIGHADDR 0x43C3FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_3 */
#define XPAR_UART_AXI_UART16550_BSM_3_BASEADDR 0x43C60000
#define XPAR_UART_AXI_UART16550_BSM_3_HIGHADDR 0x43C6FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_4 */
#define XPAR_UART_AXI_UART16550_BSM_4_BASEADDR 0x43C70000
#define XPAR_UART_AXI_UART16550_BSM_4_HIGHADDR 0x43C7FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_5 */
#define XPAR_UART_AXI_UART16550_BSM_5_BASEADDR 0x43C80000
#define XPAR_UART_AXI_UART16550_BSM_5_HIGHADDR 0x43C8FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_6 */
#define XPAR_UART_AXI_UART16550_BSM_6_BASEADDR 0x43C90000
#define XPAR_UART_AXI_UART16550_BSM_6_HIGHADDR 0x43C9FFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_7 */
#define XPAR_UART_AXI_UART16550_BSM_7_BASEADDR 0x43CA0000
#define XPAR_UART_AXI_UART16550_BSM_7_HIGHADDR 0x43CAFFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_8 */
#define XPAR_UART_AXI_UART16550_BSM_8_BASEADDR 0x43CB0000
#define XPAR_UART_AXI_UART16550_BSM_8_HIGHADDR 0x43CBFFFF


/* Peripheral Definitions for peripheral UART_AXI_UART16550_BSM_9 */
#define XPAR_UART_AXI_UART16550_BSM_9_BASEADDR 0x43CC0000
#define XPAR_UART_AXI_UART16550_BSM_9_HIGHADDR 0x43CCFFFF


/* Peripheral Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Peripheral Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Peripheral Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Peripheral Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Peripheral Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Peripheral Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Peripheral Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Peripheral Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Peripheral Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Peripheral Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Peripheral Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Peripheral Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Peripheral Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Peripheral Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFCFFFFFF


/* Peripheral Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Peripheral Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Peripheral Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Peripheral Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/******************************************************************/


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_0 */
#define XPAR_AXI_UART16550_BSM_0_BASEADDR 0x43C40000
#define XPAR_AXI_UART16550_BSM_0_HIGHADDR 0x43C4FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_1 */
#define XPAR_AXI_UART16550_BSM_1_BASEADDR 0x43C20000
#define XPAR_AXI_UART16550_BSM_1_HIGHADDR 0x43C2FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_10 */
#define XPAR_AXI_UART16550_BSM_2_BASEADDR 0x43C50000
#define XPAR_AXI_UART16550_BSM_2_HIGHADDR 0x43C5FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_11 */
#define XPAR_AXI_UART16550_BSM_3_BASEADDR 0x43D40000
#define XPAR_AXI_UART16550_BSM_3_HIGHADDR 0x43D4FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_2 */
#define XPAR_AXI_UART16550_BSM_4_BASEADDR 0x43C30000
#define XPAR_AXI_UART16550_BSM_4_HIGHADDR 0x43C3FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_3 */
#define XPAR_AXI_UART16550_BSM_5_BASEADDR 0x43C60000
#define XPAR_AXI_UART16550_BSM_5_HIGHADDR 0x43C6FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_4 */
#define XPAR_AXI_UART16550_BSM_6_BASEADDR 0x43C70000
#define XPAR_AXI_UART16550_BSM_6_HIGHADDR 0x43C7FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_5 */
#define XPAR_AXI_UART16550_BSM_7_BASEADDR 0x43C80000
#define XPAR_AXI_UART16550_BSM_7_HIGHADDR 0x43C8FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_6 */
#define XPAR_AXI_UART16550_BSM_8_BASEADDR 0x43C90000
#define XPAR_AXI_UART16550_BSM_8_HIGHADDR 0x43C9FFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_7 */
#define XPAR_AXI_UART16550_BSM_9_BASEADDR 0x43CA0000
#define XPAR_AXI_UART16550_BSM_9_HIGHADDR 0x43CAFFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_8 */
#define XPAR_AXI_UART16550_BSM_10_BASEADDR 0x43CB0000
#define XPAR_AXI_UART16550_BSM_10_HIGHADDR 0x43CBFFFF


/* Canonical Definitions for peripheral UART_AXI_UART16550_BSM_9 */
#define XPAR_AXI_UART16550_BSM_11_BASEADDR 0x43CC0000
#define XPAR_AXI_UART16550_BSM_11_HIGHADDR 0x43CCFFFF






































/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral SENSOR_MISC_AXI_GPIO_1 */
#define XPAR_SENSOR_MISC_AXI_GPIO_1_BASEADDR 0x41210000
#define XPAR_SENSOR_MISC_AXI_GPIO_1_HIGHADDR 0x4121FFFF
#define XPAR_SENSOR_MISC_AXI_GPIO_1_DEVICE_ID 0
#define XPAR_SENSOR_MISC_AXI_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_SENSOR_MISC_AXI_GPIO_1_IS_DUAL 1


/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_BASEADDR 0x41200000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4120FFFF
#define XPAR_AXI_GPIO_0_DEVICE_ID 1
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 1
#define XPAR_AXI_GPIO_0_IS_DUAL 1


/******************************************************************/

/* Canonical definitions for peripheral SENSOR_MISC_AXI_GPIO_1 */
#define XPAR_GPIO_0_BASEADDR 0x41210000
#define XPAR_GPIO_0_HIGHADDR 0x4121FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_SENSOR_MISC_AXI_GPIO_1_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 1

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_GPIO_1_BASEADDR 0x41200000
#define XPAR_GPIO_1_HIGHADDR 0x4120FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_AXI_GPIO_0_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 1
#define XPAR_GPIO_1_IS_DUAL 1


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 5

/* Definitions for peripheral IIC_AXI_IIC_0 */
#define XPAR_IIC_AXI_IIC_0_DEVICE_ID 0
#define XPAR_IIC_AXI_IIC_0_BASEADDR 0x41600000
#define XPAR_IIC_AXI_IIC_0_HIGHADDR 0x4160FFFF
#define XPAR_IIC_AXI_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_AXI_IIC_0_GPO_WIDTH 1


/* Definitions for peripheral IIC_AXI_IIC_1 */
#define XPAR_IIC_AXI_IIC_1_DEVICE_ID 1
#define XPAR_IIC_AXI_IIC_1_BASEADDR 0x41610000
#define XPAR_IIC_AXI_IIC_1_HIGHADDR 0x4161FFFF
#define XPAR_IIC_AXI_IIC_1_TEN_BIT_ADR 0
#define XPAR_IIC_AXI_IIC_1_GPO_WIDTH 1


/* Definitions for peripheral IIC_AXI_IIC_2 */
#define XPAR_IIC_AXI_IIC_2_DEVICE_ID 2
#define XPAR_IIC_AXI_IIC_2_BASEADDR 0x41620000
#define XPAR_IIC_AXI_IIC_2_HIGHADDR 0x4162FFFF
#define XPAR_IIC_AXI_IIC_2_TEN_BIT_ADR 0
#define XPAR_IIC_AXI_IIC_2_GPO_WIDTH 1


/* Definitions for peripheral IIC_AXI_IIC_3 */
#define XPAR_IIC_AXI_IIC_3_DEVICE_ID 3
#define XPAR_IIC_AXI_IIC_3_BASEADDR 0x41630000
#define XPAR_IIC_AXI_IIC_3_HIGHADDR 0x4163FFFF
#define XPAR_IIC_AXI_IIC_3_TEN_BIT_ADR 0
#define XPAR_IIC_AXI_IIC_3_GPO_WIDTH 1


/* Definitions for peripheral IIC_AXI_IIC_4 */
#define XPAR_IIC_AXI_IIC_4_DEVICE_ID 4
#define XPAR_IIC_AXI_IIC_4_BASEADDR 0x41640000
#define XPAR_IIC_AXI_IIC_4_HIGHADDR 0x4164FFFF
#define XPAR_IIC_AXI_IIC_4_TEN_BIT_ADR 0
#define XPAR_IIC_AXI_IIC_4_GPO_WIDTH 1


/******************************************************************/

/* Canonical definitions for peripheral IIC_AXI_IIC_0 */
#define XPAR_IIC_0_DEVICE_ID XPAR_IIC_AXI_IIC_0_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0x41600000
#define XPAR_IIC_0_HIGHADDR 0x4160FFFF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 1

/* Canonical definitions for peripheral IIC_AXI_IIC_1 */
#define XPAR_IIC_1_DEVICE_ID XPAR_IIC_AXI_IIC_1_DEVICE_ID
#define XPAR_IIC_1_BASEADDR 0x41610000
#define XPAR_IIC_1_HIGHADDR 0x4161FFFF
#define XPAR_IIC_1_TEN_BIT_ADR 0
#define XPAR_IIC_1_GPO_WIDTH 1

/* Canonical definitions for peripheral IIC_AXI_IIC_2 */
#define XPAR_IIC_2_DEVICE_ID XPAR_IIC_AXI_IIC_2_DEVICE_ID
#define XPAR_IIC_2_BASEADDR 0x41620000
#define XPAR_IIC_2_HIGHADDR 0x4162FFFF
#define XPAR_IIC_2_TEN_BIT_ADR 0
#define XPAR_IIC_2_GPO_WIDTH 1

/* Canonical definitions for peripheral IIC_AXI_IIC_3 */
#define XPAR_IIC_3_DEVICE_ID XPAR_IIC_AXI_IIC_3_DEVICE_ID
#define XPAR_IIC_3_BASEADDR 0x41630000
#define XPAR_IIC_3_HIGHADDR 0x4163FFFF
#define XPAR_IIC_3_TEN_BIT_ADR 0
#define XPAR_IIC_3_GPO_WIDTH 1

/* Canonical definitions for peripheral IIC_AXI_IIC_4 */
#define XPAR_IIC_4_DEVICE_ID XPAR_IIC_AXI_IIC_4_DEVICE_ID
#define XPAR_IIC_4_BASEADDR 0x41640000
#define XPAR_IIC_4_HIGHADDR 0x4164FFFF
#define XPAR_IIC_4_TEN_BIT_ADR 0
#define XPAR_IIC_4_GPO_WIDTH 1


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_I2C_0 */
#define XPAR_PS7_I2C_0_DEVICE_ID 0
#define XPAR_PS7_I2C_0_BASEADDR 0xE0004000
#define XPAR_PS7_I2C_0_HIGHADDR 0xE0004FFF
#define XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ 111111115


/* Definitions for peripheral PS7_I2C_1 */
#define XPAR_PS7_I2C_1_DEVICE_ID 1
#define XPAR_PS7_I2C_1_BASEADDR 0xE0005000
#define XPAR_PS7_I2C_1_HIGHADDR 0xE0005FFF
#define XPAR_PS7_I2C_1_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Canonical definitions for peripheral PS7_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PS7_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xE0004000
#define XPAR_XIICPS_0_HIGHADDR 0xE0004FFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 111111115

/* Canonical definitions for peripheral PS7_I2C_1 */
#define XPAR_XIICPS_1_DEVICE_ID XPAR_PS7_I2C_1_DEVICE_ID
#define XPAR_XIICPS_1_BASEADDR 0xE0005000
#define XPAR_XIICPS_1_HIGHADDR 0xE0005FFF
#define XPAR_XIICPS_1_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Definition for input Clock */
/* Definition for input Clock */
#define XPAR_INTC_MAX_NUM_INTR_INPUTS 27
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC_0 */
#define XPAR_AXI_INTC_0_DEVICE_ID 0
#define XPAR_AXI_INTC_0_BASEADDR 0x41800000
#define XPAR_AXI_INTC_0_HIGHADDR 0x4180FFFF
#define XPAR_AXI_INTC_0_KIND_OF_INTR 0xFFFFFFFF
#define XPAR_AXI_INTC_0_HAS_FAST 0
#define XPAR_AXI_INTC_0_IVAR_RESET_VALUE 0x0000000000000010
#define XPAR_AXI_INTC_0_NUM_INTR_INPUTS 27
#define XPAR_AXI_INTC_0_NUM_SW_INTR 0
#define XPAR_AXI_INTC_0_ADDR_WIDTH 32


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41800000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4180FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_AXI_INTC_0_DEVICE_ID
#define XPAR_AXI_INTC_0_TYPE 0U
#define XPAR_UART_AXI_UART16550_BSM_0_IP2INTC_IRPT_MASK 0X000001U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_0_IP2INTC_IRPT_INTR 0U
#define XPAR_UART_AXI_UART16550_BSM_1_IP2INTC_IRPT_MASK 0X000002U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_1_IP2INTC_IRPT_INTR 1U
#define XPAR_UART_AXI_UART16550_BSM_2_IP2INTC_IRPT_MASK 0X000004U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_2_IP2INTC_IRPT_INTR 2U
#define XPAR_UART_AXI_UART16550_BSM_3_IP2INTC_IRPT_MASK 0X000008U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_3_IP2INTC_IRPT_INTR 3U
#define XPAR_UART_AXI_UART16550_BSM_4_IP2INTC_IRPT_MASK 0X000010U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_4_IP2INTC_IRPT_INTR 4U
#define XPAR_UART_AXI_UART16550_BSM_5_IP2INTC_IRPT_MASK 0X000020U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_5_IP2INTC_IRPT_INTR 5U
#define XPAR_UART_AXI_UART16550_BSM_6_IP2INTC_IRPT_MASK 0X000040U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_6_IP2INTC_IRPT_INTR 6U
#define XPAR_UART_AXI_UART16550_BSM_7_IP2INTC_IRPT_MASK 0X000080U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_7_IP2INTC_IRPT_INTR 7U
#define XPAR_UART_AXI_UART16550_BSM_8_IP2INTC_IRPT_MASK 0X000100U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_8_IP2INTC_IRPT_INTR 8U
#define XPAR_UART_AXI_UART16550_BSM_9_IP2INTC_IRPT_MASK 0X000200U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_9_IP2INTC_IRPT_INTR 9U
#define XPAR_UART_AXI_UART16550_BSM_10_IP2INTC_IRPT_MASK 0X000400U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_10_IP2INTC_IRPT_INTR 10U
#define XPAR_UART_AXI_UART16550_BSM_11_IP2INTC_IRPT_MASK 0X000800U
#define XPAR_AXI_INTC_0_UART_AXI_UART16550_BSM_11_IP2INTC_IRPT_INTR 11U
#define XPAR_AXI_GPIO_0_IP2INTC_IRPT_MASK 0X001000U
#define XPAR_AXI_INTC_0_AXI_GPIO_0_IP2INTC_IRPT_INTR 12U
#define XPAR_SPI_AXI_QUAD_SPI_0_IP2INTC_IRPT_MASK 0X002000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_0_IP2INTC_IRPT_INTR 13U
#define XPAR_SPI_AXI_QUAD_SPI_1_IP2INTC_IRPT_MASK 0X004000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_1_IP2INTC_IRPT_INTR 14U
#define XPAR_SPI_AXI_QUAD_SPI_2_IP2INTC_IRPT_MASK 0X008000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_2_IP2INTC_IRPT_INTR 15U
#define XPAR_SPI_AXI_QUAD_SPI_3_IP2INTC_IRPT_MASK 0X010000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_3_IP2INTC_IRPT_INTR 16U
#define XPAR_SPI_AXI_QUAD_SPI_4_IP2INTC_IRPT_MASK 0X020000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_4_IP2INTC_IRPT_INTR 17U
#define XPAR_SPI_AXI_QUAD_SPI_5_IP2INTC_IRPT_MASK 0X040000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_5_IP2INTC_IRPT_INTR 18U
#define XPAR_SPI_AXI_QUAD_SPI_6_IP2INTC_IRPT_MASK 0X080000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_6_IP2INTC_IRPT_INTR 19U
#define XPAR_SPI_AXI_QUAD_SPI_7_IP2INTC_IRPT_MASK 0X100000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_7_IP2INTC_IRPT_INTR 20U
#define XPAR_SPI_AXI_QUAD_SPI_8_IP2INTC_IRPT_MASK 0X200000U
#define XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_8_IP2INTC_IRPT_INTR 21U
#define XPAR_IIC_AXI_IIC_0_IIC2INTC_IRPT_MASK 0X400000U
#define XPAR_AXI_INTC_0_IIC_AXI_IIC_0_IIC2INTC_IRPT_INTR 22U
#define XPAR_IIC_AXI_IIC_1_IIC2INTC_IRPT_MASK 0X800000U
#define XPAR_AXI_INTC_0_IIC_AXI_IIC_1_IIC2INTC_IRPT_INTR 23U
#define XPAR_IIC_AXI_IIC_2_IIC2INTC_IRPT_MASK 0X1000000U
#define XPAR_AXI_INTC_0_IIC_AXI_IIC_2_IIC2INTC_IRPT_INTR 24U
#define XPAR_IIC_AXI_IIC_3_IIC2INTC_IRPT_MASK 0X2000000U
#define XPAR_AXI_INTC_0_IIC_AXI_IIC_3_IIC2INTC_IRPT_INTR 25U
#define XPAR_IIC_AXI_IIC_4_IIC2INTC_IRPT_MASK 0X4000000U
#define XPAR_AXI_INTC_0_IIC_AXI_IIC_4_IIC2INTC_IRPT_INTR 26U

/******************************************************************/

/* Canonical definitions for peripheral AXI_INTC_0 */
#define XPAR_INTC_0_DEVICE_ID XPAR_AXI_INTC_0_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41800000U
#define XPAR_INTC_0_HIGHADDR 0x4180FFFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFFU
#define XPAR_INTC_0_HAS_FAST 0U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x0000000000000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 27U
#define XPAR_INTC_0_NUM_SW_INTR 0U
#define XPAR_INTC_0_ADDR_WIDTH 32U
#define XPAR_INTC_0_INTC_TYPE 0U

#define XPAR_INTC_0_GPIO_1_VEC_ID XPAR_AXI_INTC_0_AXI_GPIO_0_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_0_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_0_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_1_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_1_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_2_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_2_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_3_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_3_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_4_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_4_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_5_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_5_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_6_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_6_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_7_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_7_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SPI_8_VEC_ID XPAR_AXI_INTC_0_SPI_AXI_QUAD_SPI_8_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_0_VEC_ID XPAR_AXI_INTC_0_IIC_AXI_IIC_0_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_1_VEC_ID XPAR_AXI_INTC_0_IIC_AXI_IIC_1_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_2_VEC_ID XPAR_AXI_INTC_0_IIC_AXI_IIC_2_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_3_VEC_ID XPAR_AXI_INTC_0_IIC_AXI_IIC_3_IIC2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_4_VEC_ID XPAR_AXI_INTC_0_IIC_AXI_IIC_4_IIC2INTC_IRPT_INTR

/******************************************************************/

#define XPAR_AXI_INTC
/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_PS7_QSPI_0_QSPI_MODE 0
#define XPAR_PS7_QSPI_0_QSPI_BUS_WIDTH 2


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_XQSPIPS_0_QSPI_MODE 0
#define XPAR_XQSPIPS_0_QSPI_BUS_WIDTH 2


/******************************************************************/

/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_AXI_INTC_0_IRQ_INTR 61U

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_INTC_0_VEC_ID XPAR_FABRIC_AXI_INTC_0_IRQ_INTR

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0U
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100U
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FFU
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000U


/******************************************************************/

#define XPAR_SCUGIC
/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

#define XPAR_PS7_SCUTIMER_0_INTERRUPT XPAR_PS7_SCUTIMER_0_INTERRUPT_ID
#define XPAR_PS7_SCUTIMER_0_INTR_PARENT 0xF8F01000
/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 50000000
#define XPAR_PS7_SD_0_HAS_CD 0
#define XPAR_PS7_SD_0_HAS_WP 0
#define XPAR_PS7_SD_0_BUS_WIDTH 0
#define XPAR_PS7_SD_0_MIO_BANK 0
#define XPAR_PS7_SD_0_HAS_EMIO 0
#define XPAR_PS7_SD_0_SLOT_TYPE 0
#define XPAR_PS7_SD_0_CLK_50_SDR_ITAP_DLY 0
#define XPAR_PS7_SD_0_CLK_50_SDR_OTAP_DLY 0
#define XPAR_PS7_SD_0_CLK_50_DDR_ITAP_DLY 0
#define XPAR_PS7_SD_0_CLK_50_DDR_OTAP_DLY 0
#define XPAR_PS7_SD_0_CLK_100_SDR_OTAP_DLY 0
#define XPAR_PS7_SD_0_CLK_200_SDR_OTAP_DLY 0


/******************************************************************/

#define XPAR_PS7_SD_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000
#define XPAR_XSDPS_0_HAS_CD 0
#define XPAR_XSDPS_0_HAS_WP 0
#define XPAR_XSDPS_0_BUS_WIDTH 0
#define XPAR_XSDPS_0_MIO_BANK 0
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_SLOT_TYPE 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0
#define XPAR_XSDPS_0_CLK_50_SDR_ITAP_DLY 0
#define XPAR_XSDPS_0_CLK_50_SDR_OTAP_DLY 0
#define XPAR_XSDPS_0_CLK_50_DDR_ITAP_DLY 0
#define XPAR_XSDPS_0_CLK_50_DDR_OTAP_DLY 0
#define XPAR_XSDPS_0_CLK_100_SDR_OTAP_DLY 0
#define XPAR_XSDPS_0_CLK_200_SDR_OTAP_DLY 0


/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 9U

/* Definitions for peripheral SPI_AXI_QUAD_SPI_0 */
#define XPAR_SPI_AXI_QUAD_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_AXI_QUAD_SPI_0_BASEADDR 0x43C00000U
#define XPAR_SPI_AXI_QUAD_SPI_0_HIGHADDR 0x43C0FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_0_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_0_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_0_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_0_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_0_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_0_AXI4_BASEADDR 0x43C00000U
#define XPAR_SPI_AXI_QUAD_SPI_0_AXI4_HIGHADDR 0x43C0FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_0_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_0 */
#define XPAR_SPI_0_DEVICE_ID 0U
#define XPAR_SPI_0_BASEADDR 0x43C00000U
#define XPAR_SPI_0_HIGHADDR 0x43C0FFFFU
#define XPAR_SPI_0_FIFO_EXIST 1U
#define XPAR_SPI_0_FIFO_DEPTH 256U
#define XPAR_SPI_0_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_0_NUM_SS_BITS 3U
#define XPAR_SPI_0_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_0_SPI_MODE 0U
#define XPAR_SPI_0_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_0_AXI4_BASEADDR 0x43C00000U
#define XPAR_SPI_0_AXI4_HIGHADDR 0x43C0FFFFU
#define XPAR_SPI_0_XIP_MODE 0U
#define XPAR_SPI_0_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_1 */
#define XPAR_SPI_AXI_QUAD_SPI_1_DEVICE_ID 1U
#define XPAR_SPI_AXI_QUAD_SPI_1_BASEADDR 0x43C10000U
#define XPAR_SPI_AXI_QUAD_SPI_1_HIGHADDR 0x43C1FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_1_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_1_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_1_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_1_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_1_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_1_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_1_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_1_AXI4_BASEADDR 0x43C10000U
#define XPAR_SPI_AXI_QUAD_SPI_1_AXI4_HIGHADDR 0x43C1FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_1_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_1 */
#define XPAR_SPI_1_DEVICE_ID 1U
#define XPAR_SPI_1_BASEADDR 0x43C10000U
#define XPAR_SPI_1_HIGHADDR 0x43C1FFFFU
#define XPAR_SPI_1_FIFO_EXIST 1U
#define XPAR_SPI_1_FIFO_DEPTH 256U
#define XPAR_SPI_1_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_1_NUM_SS_BITS 3U
#define XPAR_SPI_1_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_1_SPI_MODE 0U
#define XPAR_SPI_1_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_1_AXI4_BASEADDR 0x43C10000U
#define XPAR_SPI_1_AXI4_HIGHADDR 0x43C1FFFFU
#define XPAR_SPI_1_XIP_MODE 0U
#define XPAR_SPI_1_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_2 */
#define XPAR_SPI_AXI_QUAD_SPI_2_DEVICE_ID 2U
#define XPAR_SPI_AXI_QUAD_SPI_2_BASEADDR 0x43CD0000U
#define XPAR_SPI_AXI_QUAD_SPI_2_HIGHADDR 0x43CDFFFFU
#define XPAR_SPI_AXI_QUAD_SPI_2_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_2_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_2_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_2_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_2_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_2_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_2_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_2_AXI4_BASEADDR 0x43CD0000U
#define XPAR_SPI_AXI_QUAD_SPI_2_AXI4_HIGHADDR 0x43CDFFFFU
#define XPAR_SPI_AXI_QUAD_SPI_2_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_2 */
#define XPAR_SPI_2_DEVICE_ID 2U
#define XPAR_SPI_2_BASEADDR 0x43CD0000U
#define XPAR_SPI_2_HIGHADDR 0x43CDFFFFU
#define XPAR_SPI_2_FIFO_EXIST 1U
#define XPAR_SPI_2_FIFO_DEPTH 256U
#define XPAR_SPI_2_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_2_NUM_SS_BITS 3U
#define XPAR_SPI_2_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_2_SPI_MODE 0U
#define XPAR_SPI_2_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_2_AXI4_BASEADDR 0x43CD0000U
#define XPAR_SPI_2_AXI4_HIGHADDR 0x43CDFFFFU
#define XPAR_SPI_2_XIP_MODE 0U
#define XPAR_SPI_2_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_3 */
#define XPAR_SPI_AXI_QUAD_SPI_3_DEVICE_ID 3U
#define XPAR_SPI_AXI_QUAD_SPI_3_BASEADDR 0x43CE0000U
#define XPAR_SPI_AXI_QUAD_SPI_3_HIGHADDR 0x43CEFFFFU
#define XPAR_SPI_AXI_QUAD_SPI_3_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_3_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_3_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_3_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_3_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_3_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_3_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_3_AXI4_BASEADDR 0x43CE0000U
#define XPAR_SPI_AXI_QUAD_SPI_3_AXI4_HIGHADDR 0x43CEFFFFU
#define XPAR_SPI_AXI_QUAD_SPI_3_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_3 */
#define XPAR_SPI_3_DEVICE_ID 3U
#define XPAR_SPI_3_BASEADDR 0x43CE0000U
#define XPAR_SPI_3_HIGHADDR 0x43CEFFFFU
#define XPAR_SPI_3_FIFO_EXIST 1U
#define XPAR_SPI_3_FIFO_DEPTH 256U
#define XPAR_SPI_3_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_3_NUM_SS_BITS 3U
#define XPAR_SPI_3_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_3_SPI_MODE 0U
#define XPAR_SPI_3_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_3_AXI4_BASEADDR 0x43CE0000U
#define XPAR_SPI_3_AXI4_HIGHADDR 0x43CEFFFFU
#define XPAR_SPI_3_XIP_MODE 0U
#define XPAR_SPI_3_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_4 */
#define XPAR_SPI_AXI_QUAD_SPI_4_DEVICE_ID 4U
#define XPAR_SPI_AXI_QUAD_SPI_4_BASEADDR 0x43CF0000U
#define XPAR_SPI_AXI_QUAD_SPI_4_HIGHADDR 0x43CFFFFFU
#define XPAR_SPI_AXI_QUAD_SPI_4_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_4_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_4_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_4_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_4_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_4_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_4_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_4_AXI4_BASEADDR 0x43CF0000U
#define XPAR_SPI_AXI_QUAD_SPI_4_AXI4_HIGHADDR 0x43CFFFFFU
#define XPAR_SPI_AXI_QUAD_SPI_4_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_4 */
#define XPAR_SPI_4_DEVICE_ID 4U
#define XPAR_SPI_4_BASEADDR 0x43CF0000U
#define XPAR_SPI_4_HIGHADDR 0x43CFFFFFU
#define XPAR_SPI_4_FIFO_EXIST 1U
#define XPAR_SPI_4_FIFO_DEPTH 256U
#define XPAR_SPI_4_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_4_NUM_SS_BITS 3U
#define XPAR_SPI_4_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_4_SPI_MODE 0U
#define XPAR_SPI_4_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_4_AXI4_BASEADDR 0x43CF0000U
#define XPAR_SPI_4_AXI4_HIGHADDR 0x43CFFFFFU
#define XPAR_SPI_4_XIP_MODE 0U
#define XPAR_SPI_4_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_5 */
#define XPAR_SPI_AXI_QUAD_SPI_5_DEVICE_ID 5U
#define XPAR_SPI_AXI_QUAD_SPI_5_BASEADDR 0x43D00000U
#define XPAR_SPI_AXI_QUAD_SPI_5_HIGHADDR 0x43D0FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_5_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_5_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_5_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_5_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_5_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_5_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_5_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_5_AXI4_BASEADDR 0x43D00000U
#define XPAR_SPI_AXI_QUAD_SPI_5_AXI4_HIGHADDR 0x43D0FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_5_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_5 */
#define XPAR_SPI_5_DEVICE_ID 5U
#define XPAR_SPI_5_BASEADDR 0x43D00000U
#define XPAR_SPI_5_HIGHADDR 0x43D0FFFFU
#define XPAR_SPI_5_FIFO_EXIST 1U
#define XPAR_SPI_5_FIFO_DEPTH 256U
#define XPAR_SPI_5_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_5_NUM_SS_BITS 3U
#define XPAR_SPI_5_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_5_SPI_MODE 0U
#define XPAR_SPI_5_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_5_AXI4_BASEADDR 0x43D00000U
#define XPAR_SPI_5_AXI4_HIGHADDR 0x43D0FFFFU
#define XPAR_SPI_5_XIP_MODE 0U
#define XPAR_SPI_5_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_6 */
#define XPAR_SPI_AXI_QUAD_SPI_6_DEVICE_ID 6U
#define XPAR_SPI_AXI_QUAD_SPI_6_BASEADDR 0x43D10000U
#define XPAR_SPI_AXI_QUAD_SPI_6_HIGHADDR 0x43D1FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_6_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_6_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_6_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_6_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_6_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_6_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_6_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_6_AXI4_BASEADDR 0x43D10000U
#define XPAR_SPI_AXI_QUAD_SPI_6_AXI4_HIGHADDR 0x43D1FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_6_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_6 */
#define XPAR_SPI_6_DEVICE_ID 6U
#define XPAR_SPI_6_BASEADDR 0x43D10000U
#define XPAR_SPI_6_HIGHADDR 0x43D1FFFFU
#define XPAR_SPI_6_FIFO_EXIST 1U
#define XPAR_SPI_6_FIFO_DEPTH 256U
#define XPAR_SPI_6_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_6_NUM_SS_BITS 3U
#define XPAR_SPI_6_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_6_SPI_MODE 0U
#define XPAR_SPI_6_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_6_AXI4_BASEADDR 0x43D10000U
#define XPAR_SPI_6_AXI4_HIGHADDR 0x43D1FFFFU
#define XPAR_SPI_6_XIP_MODE 0U
#define XPAR_SPI_6_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_7 */
#define XPAR_SPI_AXI_QUAD_SPI_7_DEVICE_ID 7U
#define XPAR_SPI_AXI_QUAD_SPI_7_BASEADDR 0x43D20000U
#define XPAR_SPI_AXI_QUAD_SPI_7_HIGHADDR 0x43D2FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_7_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_7_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_7_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_7_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_7_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_7_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_7_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_7_AXI4_BASEADDR 0x43D20000U
#define XPAR_SPI_AXI_QUAD_SPI_7_AXI4_HIGHADDR 0x43D2FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_7_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_7 */
#define XPAR_SPI_7_DEVICE_ID 7U
#define XPAR_SPI_7_BASEADDR 0x43D20000U
#define XPAR_SPI_7_HIGHADDR 0x43D2FFFFU
#define XPAR_SPI_7_FIFO_EXIST 1U
#define XPAR_SPI_7_FIFO_DEPTH 256U
#define XPAR_SPI_7_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_7_NUM_SS_BITS 3U
#define XPAR_SPI_7_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_7_SPI_MODE 0U
#define XPAR_SPI_7_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_7_AXI4_BASEADDR 0x43D20000U
#define XPAR_SPI_7_AXI4_HIGHADDR 0x43D2FFFFU
#define XPAR_SPI_7_XIP_MODE 0U
#define XPAR_SPI_7_USE_STARTUP 0U



/* Definitions for peripheral SPI_AXI_QUAD_SPI_8 */
#define XPAR_SPI_AXI_QUAD_SPI_8_DEVICE_ID 8U
#define XPAR_SPI_AXI_QUAD_SPI_8_BASEADDR 0x43D30000U
#define XPAR_SPI_AXI_QUAD_SPI_8_HIGHADDR 0x43D3FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_8_FIFO_EXIST 1U
#define XPAR_SPI_AXI_QUAD_SPI_8_FIFO_DEPTH 256U
#define XPAR_SPI_AXI_QUAD_SPI_8_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_AXI_QUAD_SPI_8_NUM_SS_BITS 3U
#define XPAR_SPI_AXI_QUAD_SPI_8_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_AXI_QUAD_SPI_8_SPI_MODE 0U
#define XPAR_SPI_AXI_QUAD_SPI_8_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_AXI_QUAD_SPI_8_AXI4_BASEADDR 0x43D30000U
#define XPAR_SPI_AXI_QUAD_SPI_8_AXI4_HIGHADDR 0x43D3FFFFU
#define XPAR_SPI_AXI_QUAD_SPI_8_XIP_MODE 0U

/* Canonical definitions for peripheral SPI_AXI_QUAD_SPI_8 */
#define XPAR_SPI_8_DEVICE_ID 8U
#define XPAR_SPI_8_BASEADDR 0x43D30000U
#define XPAR_SPI_8_HIGHADDR 0x43D3FFFFU
#define XPAR_SPI_8_FIFO_EXIST 1U
#define XPAR_SPI_8_FIFO_DEPTH 256U
#define XPAR_SPI_8_SPI_SLAVE_ONLY 0U
#define XPAR_SPI_8_NUM_SS_BITS 3U
#define XPAR_SPI_8_NUM_TRANSFER_BITS 8U
#define XPAR_SPI_8_SPI_MODE 0U
#define XPAR_SPI_8_TYPE_OF_AXI4_INTERFACE 1U
#define XPAR_SPI_8_AXI4_BASEADDR 0x43D30000U
#define XPAR_SPI_8_AXI4_HIGHADDR 0x43D3FFFFU
#define XPAR_SPI_8_XIP_MODE 0U
#define XPAR_SPI_8_USE_STARTUP 0U



/******************************************************************/

/* Definitions for driver SPIPS */
#define XPAR_XSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SPI_1 */
#define XPAR_PS7_SPI_1_DEVICE_ID 0
#define XPAR_PS7_SPI_1_BASEADDR 0xE0007000
#define XPAR_PS7_SPI_1_HIGHADDR 0xE0007FFF
#define XPAR_PS7_SPI_1_SPI_CLK_FREQ_HZ 166666672


/******************************************************************/

/* Canonical definitions for peripheral PS7_SPI_1 */
#define XPAR_XSPIPS_0_DEVICE_ID XPAR_PS7_SPI_1_DEVICE_ID
#define XPAR_XSPIPS_0_BASEADDR 0xE0007000
#define XPAR_XSPIPS_0_HIGHADDR 0xE0007FFF
#define XPAR_XSPIPS_0_SPI_CLK_FREQ_HZ 166666672


/******************************************************************/

/* Definitions for driver TMRCTR */
#define XPAR_XTMRCTR_NUM_INSTANCES 16U

/* Definitions for peripheral PWM_AXI_TIMER_0 */
#define XPAR_PWM_AXI_TIMER_0_DEVICE_ID 0U
#define XPAR_PWM_AXI_TIMER_0_BASEADDR 0x42800000U
#define XPAR_PWM_AXI_TIMER_0_HIGHADDR 0x4280FFFFU
#define XPAR_PWM_AXI_TIMER_0_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_1 */
#define XPAR_PWM_AXI_TIMER_1_DEVICE_ID 1U
#define XPAR_PWM_AXI_TIMER_1_BASEADDR 0x42810000U
#define XPAR_PWM_AXI_TIMER_1_HIGHADDR 0x4281FFFFU
#define XPAR_PWM_AXI_TIMER_1_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_10 */
#define XPAR_PWM_AXI_TIMER_10_DEVICE_ID 2U
#define XPAR_PWM_AXI_TIMER_10_BASEADDR 0x42820000U
#define XPAR_PWM_AXI_TIMER_10_HIGHADDR 0x4282FFFFU
#define XPAR_PWM_AXI_TIMER_10_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_11 */
#define XPAR_PWM_AXI_TIMER_11_DEVICE_ID 3U
#define XPAR_PWM_AXI_TIMER_11_BASEADDR 0x42830000U
#define XPAR_PWM_AXI_TIMER_11_HIGHADDR 0x4283FFFFU
#define XPAR_PWM_AXI_TIMER_11_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_12 */
#define XPAR_PWM_AXI_TIMER_12_DEVICE_ID 4U
#define XPAR_PWM_AXI_TIMER_12_BASEADDR 0x42840000U
#define XPAR_PWM_AXI_TIMER_12_HIGHADDR 0x4284FFFFU
#define XPAR_PWM_AXI_TIMER_12_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_13 */
#define XPAR_PWM_AXI_TIMER_13_DEVICE_ID 5U
#define XPAR_PWM_AXI_TIMER_13_BASEADDR 0x42850000U
#define XPAR_PWM_AXI_TIMER_13_HIGHADDR 0x4285FFFFU
#define XPAR_PWM_AXI_TIMER_13_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_14 */
#define XPAR_PWM_AXI_TIMER_14_DEVICE_ID 6U
#define XPAR_PWM_AXI_TIMER_14_BASEADDR 0x42860000U
#define XPAR_PWM_AXI_TIMER_14_HIGHADDR 0x4286FFFFU
#define XPAR_PWM_AXI_TIMER_14_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_15 */
#define XPAR_PWM_AXI_TIMER_15_DEVICE_ID 7U
#define XPAR_PWM_AXI_TIMER_15_BASEADDR 0x42870000U
#define XPAR_PWM_AXI_TIMER_15_HIGHADDR 0x4287FFFFU
#define XPAR_PWM_AXI_TIMER_15_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_2 */
#define XPAR_PWM_AXI_TIMER_2_DEVICE_ID 8U
#define XPAR_PWM_AXI_TIMER_2_BASEADDR 0x42880000U
#define XPAR_PWM_AXI_TIMER_2_HIGHADDR 0x4288FFFFU
#define XPAR_PWM_AXI_TIMER_2_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_3 */
#define XPAR_PWM_AXI_TIMER_3_DEVICE_ID 9U
#define XPAR_PWM_AXI_TIMER_3_BASEADDR 0x42890000U
#define XPAR_PWM_AXI_TIMER_3_HIGHADDR 0x4289FFFFU
#define XPAR_PWM_AXI_TIMER_3_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_4 */
#define XPAR_PWM_AXI_TIMER_4_DEVICE_ID 10U
#define XPAR_PWM_AXI_TIMER_4_BASEADDR 0x428A0000U
#define XPAR_PWM_AXI_TIMER_4_HIGHADDR 0x428AFFFFU
#define XPAR_PWM_AXI_TIMER_4_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_5 */
#define XPAR_PWM_AXI_TIMER_5_DEVICE_ID 11U
#define XPAR_PWM_AXI_TIMER_5_BASEADDR 0x428B0000U
#define XPAR_PWM_AXI_TIMER_5_HIGHADDR 0x428BFFFFU
#define XPAR_PWM_AXI_TIMER_5_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_6 */
#define XPAR_PWM_AXI_TIMER_6_DEVICE_ID 12U
#define XPAR_PWM_AXI_TIMER_6_BASEADDR 0x428C0000U
#define XPAR_PWM_AXI_TIMER_6_HIGHADDR 0x428CFFFFU
#define XPAR_PWM_AXI_TIMER_6_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_7 */
#define XPAR_PWM_AXI_TIMER_7_DEVICE_ID 13U
#define XPAR_PWM_AXI_TIMER_7_BASEADDR 0x428D0000U
#define XPAR_PWM_AXI_TIMER_7_HIGHADDR 0x428DFFFFU
#define XPAR_PWM_AXI_TIMER_7_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_8 */
#define XPAR_PWM_AXI_TIMER_8_DEVICE_ID 14U
#define XPAR_PWM_AXI_TIMER_8_BASEADDR 0x428E0000U
#define XPAR_PWM_AXI_TIMER_8_HIGHADDR 0x428EFFFFU
#define XPAR_PWM_AXI_TIMER_8_CLOCK_FREQ_HZ  100000000U


/* Definitions for peripheral PWM_AXI_TIMER_9 */
#define XPAR_PWM_AXI_TIMER_9_DEVICE_ID 15U
#define XPAR_PWM_AXI_TIMER_9_BASEADDR 0x428F0000U
#define XPAR_PWM_AXI_TIMER_9_HIGHADDR 0x428FFFFFU
#define XPAR_PWM_AXI_TIMER_9_CLOCK_FREQ_HZ  100000000U


/******************************************************************/

/* Canonical definitions for peripheral PWM_AXI_TIMER_0 */
#define XPAR_TMRCTR_0_DEVICE_ID 0U
#define XPAR_TMRCTR_0_BASEADDR 0x42800000U
#define XPAR_TMRCTR_0_HIGHADDR 0x4280FFFFU
#define XPAR_TMRCTR_0_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_0_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_1 */
#define XPAR_TMRCTR_1_DEVICE_ID 1U
#define XPAR_TMRCTR_1_BASEADDR 0x42810000U
#define XPAR_TMRCTR_1_HIGHADDR 0x4281FFFFU
#define XPAR_TMRCTR_1_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_1_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_10 */
#define XPAR_TMRCTR_2_DEVICE_ID 2U
#define XPAR_TMRCTR_2_BASEADDR 0x42820000U
#define XPAR_TMRCTR_2_HIGHADDR 0x4282FFFFU
#define XPAR_TMRCTR_2_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_10_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_11 */
#define XPAR_TMRCTR_3_DEVICE_ID 3U
#define XPAR_TMRCTR_3_BASEADDR 0x42830000U
#define XPAR_TMRCTR_3_HIGHADDR 0x4283FFFFU
#define XPAR_TMRCTR_3_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_11_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_12 */
#define XPAR_TMRCTR_4_DEVICE_ID 4U
#define XPAR_TMRCTR_4_BASEADDR 0x42840000U
#define XPAR_TMRCTR_4_HIGHADDR 0x4284FFFFU
#define XPAR_TMRCTR_4_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_12_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_13 */
#define XPAR_TMRCTR_5_DEVICE_ID 5U
#define XPAR_TMRCTR_5_BASEADDR 0x42850000U
#define XPAR_TMRCTR_5_HIGHADDR 0x4285FFFFU
#define XPAR_TMRCTR_5_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_13_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_14 */
#define XPAR_TMRCTR_6_DEVICE_ID 6U
#define XPAR_TMRCTR_6_BASEADDR 0x42860000U
#define XPAR_TMRCTR_6_HIGHADDR 0x4286FFFFU
#define XPAR_TMRCTR_6_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_14_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_15 */
#define XPAR_TMRCTR_7_DEVICE_ID 7U
#define XPAR_TMRCTR_7_BASEADDR 0x42870000U
#define XPAR_TMRCTR_7_HIGHADDR 0x4287FFFFU
#define XPAR_TMRCTR_7_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_15_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_2 */
#define XPAR_TMRCTR_8_DEVICE_ID 8U
#define XPAR_TMRCTR_8_BASEADDR 0x42880000U
#define XPAR_TMRCTR_8_HIGHADDR 0x4288FFFFU
#define XPAR_TMRCTR_8_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_2_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_3 */
#define XPAR_TMRCTR_9_DEVICE_ID 9U
#define XPAR_TMRCTR_9_BASEADDR 0x42890000U
#define XPAR_TMRCTR_9_HIGHADDR 0x4289FFFFU
#define XPAR_TMRCTR_9_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_3_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_4 */
#define XPAR_TMRCTR_10_DEVICE_ID 10U
#define XPAR_TMRCTR_10_BASEADDR 0x428A0000U
#define XPAR_TMRCTR_10_HIGHADDR 0x428AFFFFU
#define XPAR_TMRCTR_10_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_4_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_5 */
#define XPAR_TMRCTR_11_DEVICE_ID 11U
#define XPAR_TMRCTR_11_BASEADDR 0x428B0000U
#define XPAR_TMRCTR_11_HIGHADDR 0x428BFFFFU
#define XPAR_TMRCTR_11_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_5_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_6 */
#define XPAR_TMRCTR_12_DEVICE_ID 12U
#define XPAR_TMRCTR_12_BASEADDR 0x428C0000U
#define XPAR_TMRCTR_12_HIGHADDR 0x428CFFFFU
#define XPAR_TMRCTR_12_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_6_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_7 */
#define XPAR_TMRCTR_13_DEVICE_ID 13U
#define XPAR_TMRCTR_13_BASEADDR 0x428D0000U
#define XPAR_TMRCTR_13_HIGHADDR 0x428DFFFFU
#define XPAR_TMRCTR_13_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_7_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_8 */
#define XPAR_TMRCTR_14_DEVICE_ID 14U
#define XPAR_TMRCTR_14_BASEADDR 0x428E0000U
#define XPAR_TMRCTR_14_HIGHADDR 0x428EFFFFU
#define XPAR_TMRCTR_14_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_8_CLOCK_FREQ_HZ
/* Canonical definitions for peripheral PWM_AXI_TIMER_9 */
#define XPAR_TMRCTR_15_DEVICE_ID 15U
#define XPAR_TMRCTR_15_BASEADDR 0x428F0000U
#define XPAR_TMRCTR_15_HIGHADDR 0x428FFFFFU
#define XPAR_TMRCTR_15_CLOCK_FREQ_HZ XPAR_PWM_AXI_TIMER_9_CLOCK_FREQ_HZ

/******************************************************************/

#define XPAR_PWM_AXI_TIMER_0_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_0_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_1_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_1_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_10_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_10_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_11_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_11_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_12_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_12_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_13_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_13_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_14_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_14_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_15_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_15_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_2_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_2_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_3_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_3_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_4_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_4_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_5_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_5_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_6_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_6_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_7_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_7_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_8_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_8_INTR_PARENT 0xffff
#define XPAR_PWM_AXI_TIMER_9_INTERRUPT 0xffff
#define XPAR_PWM_AXI_TIMER_9_INTR_PARENT 0xffff
/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 3U

/* Definitions for peripheral PS7_TTC_0 */
#define XPAR_PS7_TTC_0_DEVICE_ID 0U
#define XPAR_PS7_TTC_0_BASEADDR 0XF8001000U
#define XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_0_TTC_CLK_CLKSRC 0U
#define XPAR_PS7_TTC_1_DEVICE_ID 1U
#define XPAR_PS7_TTC_1_BASEADDR 0XF8001004U
#define XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_1_TTC_CLK_CLKSRC 0U
#define XPAR_PS7_TTC_2_DEVICE_ID 2U
#define XPAR_PS7_TTC_2_BASEADDR 0XF8001008U
#define XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_PS7_TTC_2_TTC_CLK_CLKSRC 0U


/******************************************************************/

#define XPAR_PS7_TTC_0_INTERRUPT XPAR_PS7_TTC_0_INTERRUPT_ID
#define XPAR_PS7_TTC_0_INTR_PARENT 0xffff
#define XPAR_PS7_TTC_1_INTERRUPT XPAR_PS7_TTC_1_INTERRUPT_ID
#define XPAR_PS7_TTC_1_INTR_PARENT 0xffff
#define XPAR_PS7_TTC_2_INTERRUPT XPAR_PS7_TTC_2_INTERRUPT_ID
#define XPAR_PS7_TTC_2_INTR_PARENT 0xffff
/* Canonical definitions for peripheral PS7_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_PS7_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xF8001000U
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_PS7_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xF8001004U
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_PS7_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xF8001008U
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 111111115U
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_UART_0 */
#define XPAR_PS7_UART_0_DEVICE_ID 0
#define XPAR_PS7_UART_0_BASEADDR 0xE0000000
#define XPAR_PS7_UART_0_HIGHADDR 0xE0000FFF
#define XPAR_PS7_UART_0_UART_CLK_FREQ_HZ 100000000
#define XPAR_PS7_UART_0_HAS_MODEM 0


/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 1
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 100000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_0 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_0_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0000000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0000FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 100000000
#define XPAR_XUARTPS_0_HAS_MODEM 0

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_1_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_1_BASEADDR 0xE0001000
#define XPAR_XUARTPS_1_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_1_UART_CLK_FREQ_HZ 100000000
#define XPAR_XUARTPS_1_HAS_MODEM 0


/******************************************************************/

/* Definition for input Clock */
/* Definition for input Clock */
/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Xilinx FAT File System Library (XilFFs) User Settings */
#define FILE_SYSTEM_INTERFACE_SD
#define FILE_SYSTEM_FS_EXFAT
#define FILE_SYSTEM_USE_LFN 1
#define FILE_SYSTEM_USE_MKFS
#define FILE_SYSTEM_MULTI_PARTITION
#define FILE_SYSTEM_USE_CHMOD
#define FILE_SYSTEM_USE_TRIM
#define FILE_SYSTEM_NUM_LOGIC_VOL 2
#define FILE_SYSTEM_USE_STRFUNC 0
#define FILE_SYSTEM_SET_FS_RPATH 0
#define FILE_SYSTEM_WORD_ACCESS
#endif  /* end of protection macro */
